### ISSUE TITLE
Find a bug

### ISSUE THREAD

**Issue by wym6912** [ben1222/LLhelper#71]
When I placing the card ID 1172 on place 1 like this:

[![ZQZ48P.png](https://s2.ax1x.com/2019/06/29/ZQZ48P.png)](https://imgchr.com/i/ZQZ48P)

(by page /llnewunit)

and save the file, I will get an empty json file:
```json
[]
```

I found that some card on place 1 can cause this problem (like card 378 and 1172).

**Comment by ben1222** [comment]
This is caused by non-mezame card on position 1, will fix.
